---
# Copyright 2017, Logan Vig <logan2211@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Ensure the known hosts file exists
  file:
    path: "{{ ssh_client_known_hosts_file }}"
    state: touch

- name: Check the host key existence
  command: "ssh-keygen -f {{ ssh_client_known_hosts_file }} -F {{ item }}"
  with_items: "{{ ssh_known_hosts }}"
  register: ssh_known_hosts_results
  failed_when: false
  changed_when: false

- name: Add the host keys
  shell: "ssh-keyscan -H -T 10 {{ item.item }} >> {{ ssh_client_known_hosts_file }}"
  with_items: "{{ ssh_known_hosts_results.results }}"
  when:
    - item.rc != 0
